# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "ja-JP"
early_access: true
reviews:
  profile: "assertive"
  request_changes_workflow: false
  high_level_summary: true
  poem: true
  review_status: true
  collapse_walkthrough: false
  path_filters:
    - "!.godot/**"
    - "!addons/**"
    - "!assets/**"
    - "!godot_state_charts_examples/**"
    - "!**/*.import"
  auto_review:
    enabled: true
    drafts: false
chat:
  auto_reply: true
